### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by obonaventure** [cdamman/UCL2ICS#7]
L'outil semble intéressant, mais il semble envoyer aussi une invitation au professeur qui donne le cours. Ce n'est pas très pratique quand on donne cours à plus de 100 étudiants qui sont susceptibles d'utiliser l'appli...

**Comment by GuillaumeDerval** [comment]
C'est impossible, on ne fait que produire un fichier ICS (IAO n'y a que de la lecture d'ADE). Il s'agit probablement d'un étudiant qui fait une fausse manœuvre lors de l'importation du calendrier?

On va quand même investiguer :-)

**Comment by GuillaumeDerval** [comment]
De manière préventive... 70d5dc5e55ca3ab266f5d7b1435e047b78bccbd5

@cdamman tu peux mettre à jour l'application?

**Comment by cdamman** [comment]
Application mise à jour :-)
